apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    role: myrole
spec:
  containers:
    - name: web
      #image: iptcp/simple-app:0.6
      image: iptcp/simple-app:0.5
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      command: ["/bin/sh"]
      #args: ["-c", "while true; do sh app/build/distributions/app/bin/app; sleep 10;done"]
      args: ["-c", "sh app/build/distributions/app/bin/app"]



